- name: Run app
  docker_container:
    name: idwes-backapi
    image: idwes/idwes-backapi
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://idwes-postgres:5432/db