version: '3.3'
services:
  idwes-backapi:
    build: ./APIBack/simple-api-main/simple-api-main/simple-api
    networks: 
      - app-network
    depends_on: 
      - idwes-postgres 
  idwes-postgres: 
    build: ./Database
    networks: 
      - app-network
  idwes-myapache:
    build: ./HTTPServer 
    ports: 
      - 80:80
    networks: 
      - app-network
    depends_on: 
      - idwes-backapi
networks:
  app-network: